const fs = require('node:fs');
const path = require('node:path');
const lucide = require('lucide');

const root = path.resolve(__dirname, '..');
const output = path.join(root, 'assets', 'js', 'lucide.min.js');
const names = [
  'anchor','archive','badge-check','badge-dollar-sign','box','boxes','braces','building-2','calculator','check',
  'circle-help','circle-plus','code-2','contact','copy','download','eye','file-code-2','file-text','file-up','files',
  'fingerprint','globe-2','key-round','layout-grid','lock','lock-open','map-pin','message-circle-more',
  'message-square-text','moon','package','panel-left-close','panel-left-open','panels-top-left','phone','plus',
  'refresh-cw','search','shield-check','sliders-horizontal','sparkles','square-pen','sun','trash-2','truck','user',
  'workflow','x'
];
const exportName = name => name.split('-').map(part => part.charAt(0).toUpperCase() + part.slice(1)).join('');
const icons = Object.fromEntries(names.map(name => {
  const icon = lucide[exportName(name)];
  if (!Array.isArray(icon)) throw new Error(`Ícone Lucide ausente: ${name}`);
  return [name, icon];
}));
const runtime = `/* @license lucide v1.44.0 ISC; subset generated by scripts/build-icons.cjs */\n(function(g){const I=${JSON.stringify(icons)},D={xmlns:"http://www.w3.org/2000/svg",width:24,height:24,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor","stroke-width":2,"stroke-linecap":"round","stroke-linejoin":"round"};function n(t,a,c){const e=document.createElementNS("http://www.w3.org/2000/svg",t);for(const k in a)e.setAttribute(k,String(a[k]));if(c)for(const x of c)e.appendChild(n(x[0],x[1],x[2]));return e}function r(el,node,attrs){const own={};for(const a of el.attributes)if(a.name!=="data-lucide")own[a.name]=a.value;const name=el.getAttribute("data-lucide"),svg=n("svg",Object.assign({},D,own,attrs,{class:["lucide","lucide-"+name,own.class||""].filter(Boolean).join(" "),"data-lucide":name}),node);el.replaceWith(svg)}function createIcons(o={}){const root=o.root||document,attrs=o.attrs||{},els=[];if(root.matches?.("[data-lucide]"))els.push(root);els.push(...root.querySelectorAll("[data-lucide]"));for(const el of els){const name=el.getAttribute("data-lucide"),icon=I[name];if(icon)r(el,icon,attrs)}}g.lucide={createIcons,icons:I}})(window);\n`;
fs.writeFileSync(output, runtime, 'utf8');
console.log(`Subset Lucide: ${names.length} ícones, ${Buffer.byteLength(runtime)} bytes.`);
